name: CI
on: [push]
jobs:
  backend-node:
    runs-on: ubuntu-16.04
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - run: cp env-sample .env
      - name: Install dependencies
        run: npm ci

      - name: Run Lint, Tests and Coverage
        run: |
          npm run lint
          npm test
          npm run coverage
        env:
          CI: true

  frontend-angular:
    runs-on: ubuntu-16.04
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build-prod

      - name: Test
        run: npm run test-ci
